apiVersion: v1
kind: Template
metadata:
  name: building-jenkins
  namespace: openshift
  description: |-
    BuildConfig for Jenkins based on custom code usng s2i
  iconClass: icon-jenkins
  openshift.io/display-name: Jenkins BuildConfig
  openshift.io/provider-display-name: CTC Global
  tags: jenkins, build

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: jenkins-${GIT_BRANCH}
      namespace: ${PROJECT}
    spec:
      source:
        git:
          uri: ${GIT_REPO}
          ref: ${GIT_BRANCH}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins:latest
            namespace: openshift

      output:
        to:
          kind: ImageStreamTag
          name: jenkins-${GIT_BRANCH}:latest
          namespace: ${PROJECT}
    triggers: []

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        build: jenkins-${GIT_BRANCH}
      name: jenkins-${GIT_BRANCH}
      namespace: ${PROJECT}
    spec:
      lookupPolicy:
        local: false
      referencePolicy:
        type: Local

parameters:
  - name: GIT_BRANCH
    description: "Name of branch"
    value: master
  - name: PROJECT
    description: "Name of the destination project"
    value: default
  - name: GIT_REPO
    description: "URL of the repository with Jenkins configuration"
    value: https://github.com/navyasiddhu/openshift_jenkins.git
